apiVersion: v1
kind: Service
metadata:
  name: hello-custom-compute-service
spec:
  type: LoadBalancer
  selector:
    app: hello-custom-compute
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
