apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: gke-k8s-rbac-manager-cluster
spec:
  location: us-central1-a
  initialNodeCount: 1
  removeDefaultNodePool: true
  networkRef:
    name: gke-k8s-rbac-manager-net
  subnetworkRef:
    name: gke-k8s-rbac-manager-subnet
