apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: gke-k8s-rbac-manager-router
  namespace: forge-management
  labels:
    project: gcp-template-forge
    template: gke-k8s-rbac-manager
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  networkRef:
    name: gke-k8s-rbac-manager-vpc
  region: us-central1
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: gke-k8s-rbac-manager-nat
  namespace: forge-management
  labels:
    project: gcp-template-forge
    template: gke-k8s-rbac-manager
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  routerRef:
    name: gke-k8s-rbac-manager-router
  region: us-central1
  natIpAllocateOption: AUTO_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
