# Default values for latest-features-workload.
replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.25.3"

sidecar:
  enabled: true
  image: busybox
  tag: "1.36.1"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

sidecarResources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

service:
  type: ClusterIP
  port: 80

gateway:
  enabled: true
  name: latest-features-gateway
