# Default values for gke-llm-inference-gemma.
replicaCount: 1

image:
  repository: vllm/vllm-openai
  pullPolicy: IfNotPresent
  tag: "v0.7.2"

# Model configuration
model:
  name: "google/gemma-2-9b-it"
  # Path inside the bucket where weights are stored
  # GCS FUSE will mount the bucket to /data
  path: "/data"

# vLLM arguments
vllm:
  maxModelLen: 4096
  gpuMemoryUtilization: 0.9
  tensorParallelSize: 1

bucketName: "" # Provided by Terraform

serviceAccount:
  name: "gemma-sa"
  annotations: {}

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    nvidia.com/gpu: 1

nodeSelector:
  nvidia.com/gpu: "present"

tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "present"
    effect: "NoSchedule"
