apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: enterprise-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.project_id }}/secrets/{{ .Values.secrets.secretName }}/versions/latest"
        fileName: "{{ .Values.secrets.secretKey }}"
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: {{ .Values.secrets.secretName }}
spec:
  replication:
    automatic: true
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ .Values.serviceAccount.gcpServiceAccountName }}
spec:
  displayName: Enterprise Workload GSA
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: workload-identity-binding
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ .Values.serviceAccount.gcpServiceAccountName }}
  role: roles/iam.workloadIdentityUser
  member: "serviceAccount:{{ .Values.project_id }}.svc.id.goog[{{ .Release.Namespace }}/{{ .Values.serviceAccount.name }}]"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: secret-accessor-binding
spec:
  resourceRef:
    apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
    kind: SecretManagerSecret
    name: {{ .Values.secrets.secretName }}
  role: roles/secretmanager.secretAccessor
  member: "serviceAccount:{{ .Values.serviceAccount.gcpServiceAccountName }}@{{ .Values.project_id }}.iam.gserviceaccount.com"
