# Baseline values for helm deployment.
replicaCount: 1

image:
  repository: vllm/vllm-openai
  tag: v0.7.2
  pullPolicy: IfNotPresent

serviceAccountEmail: "forge-builder@gca-gke-2025.iam.gserviceaccount.com"

model:
  id: Qwen/Qwen2.5-1.5B-Instruct
  bucketName: "gca-gke-2025-gke-llm-inference-tf-weights"

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    nvidia.com/gpu: 1

nodeSelector:
  cloud.google.com/gke-accelerator: nvidia-l4

tolerations:
- key: "nvidia.com/gpu"
  operator: "Exists"
  effect: "NoSchedule"
