# Baseline values for helm lint. 
# Terraform will overwrite this file during deployment with dynamic values.
replicaCount: 1

image:
  repository: vllm/vllm-openai
  tag: v0.7.2
  pullPolicy: IfNotPresent

serviceAccountEmail: ""

model:
  id: Qwen/Qwen2.5-1.5B-Instruct
  bucketName: ""

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    nvidia.com/gpu: 1

nodeSelector:
  cloud.google.com/gke-accelerator: nvidia-l4

tolerations:
- key: "nvidia.com/gpu"
  operator: "Exists"
  effect: "NoSchedule"
