apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-workload
  labels:
    app: audit-workload
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: audit-workload
  template:
    metadata:
      labels:
        app: audit-workload
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
