apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-deployer
  template:
    metadata:
      labels:
        app: k8s-deployer
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
