# Copyright 2026 Google LLC
apiVersion: v1
kind: Namespace
metadata:
  labels:
    project: gcp-template-forge
    template: gke-kuberay-kueue-multitenant
  name: team-a
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    project: gcp-template-forge
    template: gke-kuberay-kueue-multitenant
  name: team-b
