apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gke-llm-inference-gemma.serviceAccountName" . }}
  labels:
    {{- include "gke-llm-inference-gemma.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
