apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    template: templates/6-enterprise-gke
  name: workload-sa-6
  namespace: workload-6
  annotations:
    iam.gke.io/gcp-service-account: "workload-sa-6@gca-gke-2025.iam.gserviceaccount.com"
