apiVersion: v1
kind: Service
metadata:
  name: gemma-2-2b-it-vllm
  labels:
    app: vllm-inference-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vllm-inference-server
