apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: gke-inf-fuse-cache
  namespace: forge-management
  annotations:
    cnrm.cloud.google.com/project-id: <PROJECT_ID> # UPDATE: Replace with your GCP Project ID
    cnrm.cloud.google.com/remove-default-node-pool: 'true'
  labels:
    project: gcp-template-forge
    template: gke-inference-fuse-cache
spec:
  location: <REGION> # UPDATE: Replace with your region
  networkRef:
    name: gke-inf-fuse-cache-vpc
  subnetworkRef:
    name: gke-inf-fuse-cache-subnet
  initialNodeCount: 1
  ipAllocationPolicy:
    clusterSecondaryRangeName: pods
    servicesSecondaryRangeName: services
  workloadIdentityConfig:
    workloadPool: <PROJECT_ID>.svc.id.goog # UPDATE: Replace '<PROJECT_ID>' with your GCP Project ID
  releaseChannel:
    channel: REGULAR
  addonsConfig:
    gcsFuseCsiDriverConfig:
      enabled: true
