apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  labels:
    project: gcp-template-forge
    template: gke-inference-fuse-cache-123456
  name: gke-inf-fuse-node-123456-log-writer
  namespace: forge-management
spec:
  member: serviceAccount:forge-builder@gca-gke-2025.iam.gserviceaccount.com
  role: roles/logging.logWriter
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: gca-gke-2025
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  labels:
    project: gcp-template-forge
    template: gke-inference-fuse-cache-123456
  name: gke-inf-fuse-node-123456-metric-writer
  namespace: forge-management
spec:
  member: serviceAccount:forge-builder@gca-gke-2025.iam.gserviceaccount.com
  role: roles/monitoring.metricWriter
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: gca-gke-2025
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  labels:
    project: gcp-template-forge
    template: gke-inference-fuse-cache-123456
  name: gke-inf-fuse-node-123456-registry-reader
  namespace: forge-management
spec:
  member: serviceAccount:forge-builder@gca-gke-2025.iam.gserviceaccount.com
  role: roles/artifactregistry.reader
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: gca-gke-2025
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  labels:
    project: gcp-template-forge
    template: gke-inference-fuse-cache-123456
  name: gke-inf-fuse-workload-123456-bucket-access
  namespace: forge-management
spec:
  member: serviceAccount:forge-builder@gca-gke-2025.iam.gserviceaccount.com
  role: roles/storage.objectAdmin
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: gke-inf-fuse-cache-123456-kcc-bucket
