apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: gke-inf-fuse-cache-vpc
  namespace: forge-management
  annotations:
    cnrm.cloud.google.com/project-id: <PROJECT_ID> # UPDATE: Replace with your GCP Project ID
  labels:
    project: gcp-template-forge
    template: gke-inference-fuse-cache
spec:
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: gke-inf-fuse-cache-subnet
  namespace: forge-management
  annotations:
    cnrm.cloud.google.com/project-id: <PROJECT_ID> # UPDATE: Replace with your GCP Project ID
  labels:
    project: gcp-template-forge
    template: gke-inference-fuse-cache
spec:
  ipCidrRange: 10.10.0.0/20
  region: <REGION> # UPDATE: Replace with your region
  networkRef:
    name: gke-inf-fuse-cache-vpc
  privateIpGoogleAccess: true
  secondaryIpRange:
  - rangeName: pods
    ipCidrRange: 10.14.0.0/14
  - rangeName: services
    ipCidrRange: 10.18.0.0/20
