apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  labels:
    project: gcp-template-forge
    template: gke-inference-fuse-cache
  name: gke-inf-fuse-cache-sys
  namespace: forge-management
spec:
  clusterRef:
    name: gke-inf-fuse-cache
  location: <REGION>
  nodeLocations:
  - <REGION>-a
  nodeCount: 1
  nodeConfig:
    machineType: e2-standard-4
    diskSizeGb: 50
    diskType: pd-balanced
    serviceAccountRef:
      name: gke-inf-fuse-node
    oauthScopes:
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/devstorage.read_only
    labels:
      project: gcp-template-forge
      template: gke-inference-fuse-cache
      pool: system
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  labels:
    project: gcp-template-forge
    template: gke-inference-fuse-cache
  name: gke-inf-fuse-cache-gpu
  namespace: forge-management
spec:
  clusterRef:
    name: gke-inf-fuse-cache
  location: <REGION>
  nodeLocations:
  - <REGION>-a
  - <REGION>-b
  - <REGION>-c
  autoscaling:
    totalMinNodeCount: 0
    totalMaxNodeCount: 1
    locationPolicy: ANY
  nodeConfig:
    machineType: g2-standard-4
    diskSizeGb: 100
    diskType: pd-balanced
    ephemeralStorageLocalSsdConfig:
      localSsdCount: 1
    guestAccelerator:
    - type: nvidia-l4
      count: 1
      gpuDriverInstallationConfig:
        gpuDriverVersion: DEFAULT
    serviceAccountRef:
      name: gke-inf-fuse-node
    oauthScopes:
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/devstorage.read_only
    labels:
      project: gcp-template-forge
      template: gke-inference-fuse-cache
      pool: gpu
      cloud.google.com/gke-accelerator: nvidia-l4
    taint:
    - key: nvidia.com/gpu
      value: present
      effect: NO_SCHEDULE
