apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "3"
  name: default-flavor
spec:
  nodeLabels:
    gpu: "l4" # Match our node pool

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "3"
  name: team-a-cq
spec:
  cohort: shared-gpus
  resourceGroups:
  - coveredResources: ["nvidia.com/gpu"]
    flavors:
    - name: default-flavor
      resources:
      - name: "nvidia.com/gpu"
        nominalQuota: 1
        borrowingLimit: 1

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "3"
  name: team-b-cq
spec:
  cohort: shared-gpus
  resourceGroups:
  - coveredResources: ["nvidia.com/gpu"]
    flavors:
    - name: default-flavor
      resources:
      - name: "nvidia.com/gpu"
        nominalQuota: 1
        borrowingLimit: 1

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "3"
  name: team-a-queue
  namespace: team-a
spec:
  clusterQueue: team-a-cq

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "3"
  name: team-b-queue
  namespace: team-b
spec:
  clusterQueue: team-b-cq
