apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  labels:
    kueue.x-k8s.io/queue-name: team-a-queue
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
  labels:
    kueue.x-k8s.io/queue-name: team-b-queue
