apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: ray-kueue-kcc-vpc
  namespace: forge-management
  labels:
    project: gcp-template-forge
spec:
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: ray-kueue-kcc-subnet
  namespace: forge-management
  labels:
    project: gcp-template-forge
spec:
  ipCidrRange: 10.20.0.0/16
  region: us-central1
  networkRef:
    name: ray-kueue-kcc-vpc
