# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  labels:
    project: gcp-template-forge
    template: gke-kuberay-kueue-multitenant
  name: gke-kuberay-kueue-multitenant-sys
  namespace: forge-management # UPDATE: Replace with your KCC namespace
spec:
  clusterRef:
    name: gke-kuberay-kueue-multitenant
  location: us-central1
  nodeCount: 1
  nodeConfig:
    machineType: e2-standard-4
    diskSizeGb: 50
    diskType: pd-balanced
    serviceAccountRef:
      name: gke-ray-multitenant-node
    oauthScopes:
    - https://www.googleapis.com/auth/cloud-platform
    labels:
      project: gcp-template-forge
      template: gke-kuberay-kueue-multitenant
      pool: system
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  labels:
    project: gcp-template-forge
    template: gke-kuberay-kueue-multitenant
  name: gke-kuberay-kueue-multitenant-gpu
  namespace: forge-management # UPDATE: Replace with your KCC namespace
spec:
  clusterRef:
    name: gke-kuberay-kueue-multitenant
  location: us-central1
  autoscaling:
    totalMinNodeCount: 0
    totalMaxNodeCount: 5
    locationPolicy: BALANCED
  nodeConfig:
    machineType: g2-standard-4
    diskSizeGb: 100
    diskType: pd-balanced
    guestAccelerator:
    - type: nvidia-l4
      count: 1
      gpuDriverInstallationConfig:
        gpuDriverVersion: DEFAULT
    serviceAccountRef:
      name: gke-ray-multitenant-node
    oauthScopes:
    - https://www.googleapis.com/auth/cloud-platform
    labels:
      project: gcp-template-forge
      template: gke-kuberay-kueue-multitenant
      pool: gpu
      cloud.google.com/gke-accelerator: nvidia-l4
    taint:
    - key: nvidia.com/gpu
      value: present
      effect: NO_SCHEDULE
