# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: gke-kuberay-kueue-multitenant-s
  namespace: forge-management
  labels:
    project: gcp-template-forge
    template: gke-kuberay-kueue-multitenant
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025 # UPDATE: Replace with your GCP Project ID
spec:
  clusterRef:
    name: gke-kuberay-kueue-multitenant
  location: us-central1 # UPDATE: Replace with your region
  nodeLocations:
    - us-central1-a # UPDATE: Replace with your zone
  nodeCount: 1
  nodeConfig:
    spot: false
    machineType: e2-standard-4
    diskSizeGb: 50
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
    labels:
      project: gcp-template-forge
      template: gke-kuberay-kueue-multitenant
      pool: system
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: gke-kuberay-kueue-multitenant-g
  namespace: forge-management
  labels:
    project: gcp-template-forge
    template: gke-kuberay-kueue-multitenant
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025 # UPDATE: Replace with your GCP Project ID
spec:
  clusterRef:
    name: gke-kuberay-kueue-multitenant
  location: us-central1 # UPDATE: Replace with your region
  nodeLocations:
    - us-central1-a # UPDATE: Replace with your zone
    - us-central1-b # UPDATE: Replace with your zone
    - us-central1-c # UPDATE: Replace with your zone
  autoscaling:
    minNodeCount: 0
    totalMaxNodeCount: 5
    locationPolicy: BALANCED
  nodeConfig:
    spot: false
    machineType: g2-standard-4
    diskSizeGb: 100
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
    guestAccelerator:
      - type: nvidia-l4
        count: 1
        gpuDriverInstallationConfig:
          gpuDriverVersion: DEFAULT
    labels:
      project: gcp-template-forge
      template: gke-kuberay-kueue-multitenant
      pool: gpu
      "cloud.google.com/gke-accelerator": nvidia-l4
    taint:
      - key: nvidia.com/gpu
        value: present
        effect: NO_SCHEDULE
