apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: gca-gke-2025-gke-vllm-staging-weights-kcc
  namespace: forge-management
  labels:
    template: gke-vllm-staging
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  location: us-central1
  storageClass: STANDARD
  uniformBucketLevelAccess: true
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: gke-vllm-staging-kcc-bucket-iam
  namespace: forge-management
  labels:
    template: gke-vllm-staging
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  member: serviceAccount:forge-builder@gca-gke-2025.iam.gserviceaccount.com
  role: roles/storage.objectAdmin
  resourceRef:
    kind: StorageBucket
    name: gca-gke-2025-gke-vllm-staging-weights-kcc
