apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: cluster-issue-6-kcc
  namespace: forge-management
  labels:
    template: templates/6-enterprise-gke
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  location: us-central1
  initialNodeCount: 1
  removeDefaultNodePool: true
  networkingMode: VPC_NATIVE
  networkRef:
    name: vpc-issue-6-kcc
  subnetworkRef:
    name: subnet-issue-6-kcc
  ipAllocationPolicy:
    clusterSecondaryRangeName: pods
    servicesSecondaryRangeName: services
  privateClusterConfig:
    enablePrivateNodes: true
    enablePrivateEndpoint: false
    masterIpv4CidrBlock: "172.16.206.0/28"
  workloadIdentityConfig:
    workloadPool: "gca-gke-2025.svc.id.goog"
  networkPolicy:
    enabled: true
    provider: CALICO
  binaryAuthorization:
    evaluationMode: PROJECT_SINGLETON_POLICY_ENFORCE
  loggingConfig:
    enableComponents:
      - SYSTEM_COMPONENTS
      - WORKLOADS
  monitoringConfig:
    enableComponents:
      - SYSTEM_COMPONENTS
    managedPrometheus:
      enabled: true
  securityPostureConfig:
    mode: BASIC
    vulnerabilityMode: VULNERABILITY_ENTERPRISE
  secretManagerConfig:
    enabled: true
  releaseChannel:
    channel: REGULAR
