apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: enterprise-workload-sa
  namespace: forge-management
  labels:
    template: templates/6-enterprise-gke
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  displayName: "Enterprise Workload Service Account"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: workload-identity-binding
  namespace: forge-management
  labels:
    template: templates/6-enterprise-gke
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  member: "serviceAccount:gca-gke-2025.svc.id.goog[default/enterprise-workload-sa]"
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: enterprise-workload-sa
