apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: router-issue-6-kcc
  namespace: forge-management
  labels:
    template: templates/6-enterprise-gke
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  region: us-central1
  networkRef:
    name: vpc-issue-6-kcc
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: nat-issue-6-kcc
  namespace: forge-management
  labels:
    template: templates/6-enterprise-gke
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  region: us-central1
  routerRef:
    name: router-issue-6-kcc
  natIpAllocateOption: AUTO_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
  logConfig:
    enable: true
    filter: ERRORS_ONLY
