apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: vpc-issue-6-kcc
  namespace: forge-management
  labels:
    template: templates/6-enterprise-gke
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: subnet-issue-6-kcc
  namespace: forge-management
  labels:
    template: templates/6-enterprise-gke
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  ipCidrRange: 10.6.0.0/20
  region: us-central1
  networkRef:
    name: vpc-issue-6-kcc
  privateIpGoogleAccess: true
  secondaryIpRange:
    - rangeName: pods
      ipCidrRange: 10.16.0.0/16
    - rangeName: services
      ipCidrRange: 172.16.6.0/20
