apiVersion: v1
kind: ServiceAccount
metadata:
  name: enterprise-workload-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: "enterprise-workload-sa@gca-gke-2025.iam.gserviceaccount.com"
