apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  labels:
    project: gcp-template-forge
    template: k8s-deployer
  name: k8s-deployer-kcc
spec:
  location: us-central1
  initialNodeCount: 1
  removeDefaultNodePool: true
  networkRef:
    name: k8s-deployer-kcc-vpc
  subnetworkRef:
    name: k8s-deployer-kcc-subnet
  ipAllocationPolicy:
    clusterSecondaryRangeName: pods
    servicesSecondaryRangeName: services
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  labels:
    project: gcp-template-forge
    template: k8s-deployer
  name: k8s-deployer-kcc-pool
spec:
  clusterRef:
    name: k8s-deployer-kcc
  location: us-central1
  nodeCount: 1
  nodeConfig:
    machineType: e2-standard-2
    diskSizeGb: 50
    spot: true
    oauthScopes:
      - "https://www.googleapis.com/auth/cloud-platform"
