{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "enterprise-workload.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "enterprise-workload.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount }}
{{- end }}
