apiVersion: v2
name: workload
description: A Helm chart for multitenant Kueue + Kuberay
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kuberay-operator
    version: 1.6.1
    repository: https://ray-project.github.io/kuberay-helm/
