apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: gca-gke-2025-gke-llm-inference-kcc-weights
  namespace: forge-management
  labels:
    template: gke-llm-inference
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  location: us-central1
  uniformBucketLevelAccess: true
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: gke-llm-inference-kcc-sa
  namespace: forge-management
  labels:
    template: gke-llm-inference
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  displayName: GKE LLM Inference KCC Workload Service Account
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: gke-llm-inference-kcc-sa-workload-identity
  namespace: forge-management
  labels:
    template: gke-llm-inference
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: gke-llm-inference-kcc-sa
  role: roles/iam.workloadIdentityUser
  member: serviceAccount:gca-gke-2025.svc.id.goog[default/gemma-2-2b-it-vllm-sa]
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: gke-llm-inference-kcc-sa-storage-admin
  namespace: forge-management
  labels:
    template: gke-llm-inference
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: gca-gke-2025-gke-llm-inference-kcc-weights
  role: roles/storage.objectAdmin
  member: serviceAccount:gke-llm-inference-kcc-sa@gca-gke-2025.iam.gserviceaccount.com
