apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: gke-llm-inference-kcc-vpc
  namespace: forge-management
  labels:
    template: gke-llm-inference
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: gke-llm-inference-kcc-subnet
  namespace: forge-management
  labels:
    template: gke-llm-inference
  annotations:
    cnrm.cloud.google.com/project-id: gca-gke-2025
spec:
  ipCidrRange: 10.32.0.0/20
  region: us-central1
  networkRef:
    name: gke-llm-inference-kcc-vpc
  privateIpGoogleAccess: true
  secondaryIpRange:
  - rangeName: pods
    ipCidrRange: 10.36.0.0/14
  - rangeName: services
    ipCidrRange: 10.40.0.0/20
