apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enterprise-workload.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "enterprise-workload.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
