{{- if and .Values.secrets .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.providerClass }}
  labels:
    app.kubernetes.io/name: {{ include "enterprise-workload.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secrets.gcpProjectId | default "gca-gke-2025" }}/secrets/{{ .Values.secrets.secretName | default "workload-6-secret" }}/versions/{{ .Values.secrets.secretVersion | default "latest" }}"
        path: "secret.data"
{{- end }}
