apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployer-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: k8s-deployer
  template:
    metadata:
      labels:
        app: k8s-deployer
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
