apiVersion: gcp.solutions.com/v1
kind: TemplateMetadata
metadata:
  name: kuberay-kueue
spec:
  shortName: kuberay-kueue
  displayName: KubeRay Kueue Cluster
  description: GKE Cluster with KubeRay and Kueue integration for advanced ML workload scheduling.
  gcpServices:
    - GKE
    - Compute
  issueNumber: 1
