apiVersion: networking.gke.io/v1alpha1
kind: FQDNNetworkPolicy
metadata:
  name: allow-ai-egress
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.pod.label }}
  egress:
  - matches:
    - name: api.anthropic.com
    - name: huggingface.co
    ports:
    - protocol: TCP
      port: 443
