apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher-service
  labels:
    app: watcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher-service
  template:
    metadata:
      labels:
        app: watcher-service
    spec:
      containers:
        - name: watcher
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: watcher-service
spec:
  type: LoadBalancer
  selector:
    app: watcher-service
  ports:
    - port: 80
      targetPort: 80
