apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  location: ${REGION}
  networkRef:
    name: ${NET_NAME}
  subnetworkRef:
    name: ${SUBNET_NAME}
  ipAllocationPolicy:
    clusterSecondaryRangeName: pods
    servicesSecondaryRangeName: services
  releaseChannel:
    channel: REGULAR
  workloadIdentityConfig:
    workloadPool: gca-gke-2025.svc.id.goog
  removeDefaultNodePool: true
  initialNodeCount: 1
