apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: ci-bug-readme-in-tem-cluster
spec:
  location: us-central1
  initialNodeCount: 1
  removeDefaultNodePool: true
  networkRef:
    name: ci-bug-readme-in-tem-vpc
  subnetworkRef:
    name: ci-bug-readme-in-tem-subnet
  ipAllocationPolicy:
    useIpAliases: true
  workloadIdentityConfig:
    workloadPool: gca-gke-2025.svc.id.goog
