apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  location: ${REGION}
  initialNodeCount: 1
  networkRef:
    name: ${NETWORK_NAME}
  subnetworkRef:
    name: ${SUBNET_NAME}
  workloadIdentityConfig:
    workloadPool: gca-gke-2025.svc.id.goog
  removeDefaultNodePool: true
  addonsConfig:
    gcsFuseCsiDriverConfig:
      enabled: true
  gatewayApiConfig:
    channel: CHANNEL_STANDARD
