apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
   name: ${NETWORK_NAME}
spec:
  autoCreateSubnetworks: false
  routingMode: REGIONAL
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: ${SUBNET_NAME}
spec:
  region: ${REGION}
  networkRef:
    name: ${NETWORK_NAME}
  ipCidrRange: 10.0.0.0/16
  privateIpGoogleAccess: true
