apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: ${CLUSTER_NAME}-np
spec:
  location: ${REGION}
  clusterRef:
    name: ${CLUSTER_NAME}
  initialNodeCount: 1
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 3
  nodeConfig:
    machineType: e2-standard-4
    diskSizeGb: 50
    diskType: pd-standard
    oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
  nodeLocations:
    - ${ZONE}
