apiVersion: v1
kind: Service
metadata:
  name: {{ include "workload.fullname" . }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    app: spot-app
    {{- include "workload.selectorLabels" . | nindent 4 }}
