apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: test-workload-bucket
  namespace: config-connector # Or the target namespace
spec:
  location: US
  storageClass: STANDARD
  uniformBucketLevelAccess: true
