apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: kcc-template-online-net
spec:
  autoCreateSubnetworks: false
  routingMode: REGIONAL
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: kcc-template-online-subnet
spec:
  region: us-central1
  ipCidrRange: 10.128.0.0/20
  networkRef:
    name: kcc-template-online-net
  privateIpGoogleAccess: true
