# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-llm-inference-gemma
  namespace: gemma
spec:
  replicaCount: 1
  selector:
    matchLabels:
      app: gke-llm-inference-gemma
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app: gke-llm-inference-gemma
    spec:
      serviceAccountName: gemma-sa
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.5.3
          command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
          args:
            - "--model"
            - "google/gemma-2-9b-it"
            - "--load-format"
            - "safetensors"
            - "--gpu-memory-utilization"
            - "0.9"
            - "--max-model-len"
            - "4096"
          ports:
            - name: http
              containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /data
              name: gcs-fuse-csi-ephemeral
              readOnly: true
      volumes:
        - name: gcs-fuse-csi-ephemeral
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: gca-gke-2025-gemma-weights-kcc
              mountOptions: "implicit-dirs"
      nodeSelector:
        nvidia.com/gpu: present
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: present
          effect: NoSchedule
