apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: enterprise-workload-pdb
  namespace: enterprise-workload
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: enterprise-workload
