apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    template: templates/6-enterprise-gke
  name: workload-6-pdb
  namespace: workload-6
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: workload-6
