apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: enterprise-workload
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: enterprise-workload
