apiVersion: v1
kind: Namespace
metadata:
  name: gemma
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: l4-flavor
spec:
  nodeLabels:
    "nvidia.com/gpu": "present"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-queue
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu"]
      flavors:
        - name: l4-flavor
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: "1"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: local-queue
  namespace: gemma
spec:
  clusterQueue: cluster-queue
