name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  kcc-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Run KCC Validation
      run: |
        cd templates/6-enterprise-gke
        ./validate.sh
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

  helm-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Helm
      uses: azure/setup-helm@v4
    - name: Helm Lint
      run: |
        cd templates/6-enterprise-gke/workload
        helm lint .
    - name: Helm Template
      run: |
        cd templates/6-enterprise-gke/workload
        helm template .
